# Supplementary Figure S4: Condition Centroid Analysis

- Figure / panels: `FigS4`
- Inputs: result payloads for the selected datasets
- Outputs: `artifacts/paper_figures/supp/FigS4_CentroidAnalysis/*`
- Run order: optional; run after the main benchmark notebooks
- Dataset selector: edit `SELECTED_DATASET_KEYS` in the parameter cell below
- Role: Supplementary

In [1]:
from __future__ import annotations

import importlib
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
from IPython.display import display

repo_root = Path.cwd().resolve()
while repo_root != repo_root.parent and not (repo_root / 'scripts').exists():
    repo_root = repo_root.parent
if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))
if str(repo_root / 'src') not in sys.path:
    sys.path.insert(0, str(repo_root / 'src'))

from scripts.common.paper_plot_style import apply_gears_paper_style
import scripts.trishift.analysis._result_adapter as _result_adapter
import scripts.trishift.analysis.condition_centroid_vis as condition_centroid_vis

apply_gears_paper_style(font_scale=1.0)
importlib.reload(condition_centroid_vis)

D:\conda_envs\biolord\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
ALL_DATASET_SPECS = [
    {'dataset_key': 'dixit', 'dataset_label': 'Dixit'},
    {'dataset_key': 'adamson', 'dataset_label': 'Adamson'},
    {'dataset_key': 'norman', 'dataset_label': 'Norman'},
    {'dataset_key': 'replogle_k562_essential', 'dataset_label': 'Replogle K562'},
    {'dataset_key': 'replogle_rpe1_essential', 'dataset_label': 'Replogle RPE1'},
]
AVAILABLE_DATASET_KEYS = [spec['dataset_key'] for spec in ALL_DATASET_SPECS]
SELECTED_DATASET_KEYS = ['adamson', 'norman']  # edit here
invalid_dataset_keys = [key for key in SELECTED_DATASET_KEYS if key not in AVAILABLE_DATASET_KEYS]
if invalid_dataset_keys:
    raise ValueError(f'Unknown dataset keys: {invalid_dataset_keys}. Available: {AVAILABLE_DATASET_KEYS}')
DATASET_SPECS = [spec for spec in ALL_DATASET_SPECS if spec['dataset_key'] in SELECTED_DATASET_KEYS]
if not DATASET_SPECS:
    raise ValueError('SELECTED_DATASET_KEYS produced an empty dataset list.')

MODELS = ['trishift', 'biolord', 'gears', 'genepert', 'scgpt']  # edit here
VARIANT_TAGS = {'trishift': 'nearest'}
AVAILABLE_SPLIT_IDS = [1, 2, 3, 4, 5]
SELECTED_SPLIT_IDS = AVAILABLE_SPLIT_IDS.copy()  # edit here
invalid_split_ids = [split_id for split_id in SELECTED_SPLIT_IDS if split_id not in AVAILABLE_SPLIT_IDS]
if invalid_split_ids:
    raise ValueError(f'Unknown split ids: {invalid_split_ids}. Available: {AVAILABLE_SPLIT_IDS}')
SPLIT_IDS = [int(split_id) for split_id in SELECTED_SPLIT_IDS]
OUT_ROOT = repo_root / 'artifacts' / 'paper_figures' / 'supp' / 'FigS4_CentroidAnalysis'
OUT_ROOT.mkdir(parents=True, exist_ok=True)
summary_frames = []
print('Selected datasets:', SELECTED_DATASET_KEYS)
print('Selected splits:', SPLIT_IDS)
print('Selected models:', MODELS)
for spec in DATASET_SPECS:
    for split_id in SPLIT_IDS:
        for model_name in MODELS:
            try:
                result = condition_centroid_vis.run_condition_centroid_visualization(model_name=model_name, dataset=spec['dataset_key'], split_id=split_id, variant_tag=VARIANT_TAGS.get(model_name, ''), feature_mode='deg', include_ctrl=True, plot_delta=True, out_root=OUT_ROOT / spec['dataset_key'] / f'{model_name}_split{split_id}')
            except Exception:
                continue
            df = result.summary_df.copy(); df['dataset_label'] = spec['dataset_label']; df['model_name'] = model_name; df['split_id'] = split_id; summary_frames.append(df)
summary_df = pd.concat(summary_frames, ignore_index=True) if summary_frames else pd.DataFrame()
summary_df.to_csv(OUT_ROOT / 'figs4_summary_all.csv', index=False, encoding='utf-8-sig')
display(summary_df.head())
print(OUT_ROOT)

Selected datasets: ['adamson', 'norman']
Selected splits: [1, 2, 3, 4, 5]
Selected models: ['trishift', 'biolord', 'gears', 'genepert', 'scgpt']

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

,n_conditions,n_splits,centroid_dist_mean,centroid_dist_median,centroid_dist_std,delta_centroid_dist_mean,delta_centroid_dist_median,delta_centroid_dist_std,centroid_cosine_mean,centroid_cosine_median,...,dataset,split_id,feature_mode,variant_tag,include_ctrl,plot_delta,umap_n_neighbors,umap_min_dist,embed_mode,dataset_label
0,17,1,0.914067,0.686243,0.664362,0.914067,0.686243,0.664361,0.996842,0.998733,...,adamson,1,deg,nearest,True,True,15,0.15,umap,Adamson
1,17,1,2.391357,2.055250,0.842307,2.391357,2.055250,0.842307,0.984319,0.990055,...,adamson,1,deg,,True,True,15,0.15,umap,Adamson
2,16,1,1.162791,0.870010,0.881956,1.162791,0.870010,0.881956,0.994752,0.998071,...,adamson,1,deg,,True,True,15,0.15,umap,Adamson
3,17,1,1.092259,0.605314,1.036716,1.092259,0.605314,1.036716,0.994180,0.998879,...,adamson,1,deg,,True,True,15,0.15,umap,Adamson
4,17,1,1.361081,0.897468,1.014497,1.361081,0.897468,1.014497,0.993042,0.998588,...,adamson,1,deg,,True,True,15,0.15,umap,Adamson

E:\CODE\trishift\artifacts\paper_figures\supp\FigS4_CentroidAnalysis

## FigS4a-b Outputs

- `FigS4a`: 5-split mean bar charts for `delta_cosine_mean` and `delta_centroid_dist_mean`
- `FigS4b`: Norman delta-centroid UMAP grid (rows = models, columns = splits)

In [3]:
from matplotlib.patches import Patch
import numpy as np
import seaborn as sns
import scipy.sparse as sp
import json as _json

from scripts.systema._core import baselines_core as systema_core
from scripts.common.split_utils import split_by_dataset_policy

MODEL_DISPLAY = {
    'trishift': 'TriShift',
    'gears': 'GEARS',
    'genepert': 'GenePert',
    'scgpt': 'scGPT',
    'biolord': 'biolord',
    'systema_matching_mean': 'Matching mean',
}
MODEL_COLORS = {
    'TriShift': '#E69F00',
    'GEARS': '#D55E00',
    'GenePert': '#009E73',
    'scGPT': '#CC79A7',
    'biolord': '#0072B2',
    'Matching mean': '#7A6FF0',
}
MODEL_ORDER = ['trishift', 'biolord', 'gears', 'genepert', 'scgpt', 'systema_matching_mean']
REPRESENTATIVE_MODEL_ORDER = ['trishift', 'biolord', 'gears', 'genepert', 'scgpt', 'systema_matching_mean']
DATASET_ORDER = ['Norman']

def _dense_2d(x):
    if sp.issparse(x):
        return x.toarray().astype(np.float32, copy=False)
    return np.asarray(x, dtype=np.float32)


def _prepare_systema_assets(dataset_key: str, split_ids: list[int], out_root: Path) -> pd.DataFrame:
    target_root = out_root / dataset_key
    target_root.mkdir(parents=True, exist_ok=True)
    systema_run_root = repo_root / 'artifacts' / 'results' / dataset_key / _result_adapter.default_systema_root(dataset_key).name / 'systema_matching_mean'
    if not systema_run_root.exists():
        return pd.DataFrame()
    systema_metrics = pd.read_csv(systema_run_root / 'metrics.csv')

    paths_cfg = systema_core.load_yaml(str(repo_root / 'configs' / 'paths.yaml'))
    h5ad_path = Path(paths_cfg['datasets'][dataset_key])
    if not h5ad_path.is_absolute():
        h5ad_path = repo_root / h5ad_path
    emb_key = systema_core.DATASET_CONFIG[dataset_key]['emb_key']
    emb_path = Path(paths_cfg['embeddings'][emb_key])
    if not emb_path.is_absolute():
        emb_path = repo_root / emb_path

    adata = systema_core.load_adata(str(h5ad_path))
    adata.uns = {}
    embd_df = systema_core.load_embedding_df(str(emb_path))
    embd_df = systema_core.apply_alias_mapping(embd_df, dataset_key)
    degs_cache_path = repo_root / 'artifacts' / 'cache' / 'degs' / f'{dataset_key}_degs.pkl'
    degs_cache = systema_core._load_degs_cache(degs_cache_path)
    if degs_cache:
        adata.uns.update(degs_cache)
    data = systema_core.TriShiftData(adata, embd_df)
    data.setup_embedding_index()
    data.build_or_load_degs()

    X_all = data.adata_all.X
    cond_series = data.adata_all.obs[data.label_key].astype(str).values
    var_names = np.asarray(data.adata_all.var_names).astype(str)
    summary_rows = []

    for split_id in split_ids:
        split_dict = split_by_dataset_policy(data, dataset_name=dataset_key, seed=int(split_id))
        train_adata = split_dict['train']
        train_ctrl_adata = systema_core._ctrl_pool_from_split(data, train_adata)
        mu_pert = systema_core._systema_nonctl_mean_mu(train_adata)
        train_cond_set = set(train_adata.obs[data.label_key].astype(str).unique().tolist())
        centroid_cache = {}
        conds = systema_metrics.loc[systema_metrics['split_id'] == int(split_id), 'condition'].astype(str).tolist()
        global_genes = sorted({gene for cond in conds for gene in var_names[np.asarray(systema_core._get_deg_idx(data, cond), dtype=int)].tolist()})
        global_genes_arr = np.asarray(global_genes, dtype=object)
        point_rows = []
        metric_rows = []

        for cond in conds:
            deg_idx = np.asarray(systema_core._get_deg_idx(data, cond), dtype=int)
            if deg_idx.size == 0:
                continue
            truth_mask = cond_series == str(cond)
            if not np.any(truth_mask):
                continue
            pred_mean = systema_core._systema_matching_mean_mu(
                condition=str(cond),
                train_adata=train_adata,
                train_cond_set=train_cond_set,
                mu_pert=mu_pert,
                centroid_cache=centroid_cache,
            )
            truth = _dense_2d(X_all[truth_mask][:, deg_idx])
            ctrl = _dense_2d(train_ctrl_adata[:, deg_idx].X)
            pred = np.asarray(pred_mean[deg_idx], dtype=np.float32).reshape(1, -1)
            genes = var_names[deg_idx]
            cur_points, cur_metric = condition_centroid_vis._centroid_rows(
                condition=str(cond),
                split_id=int(split_id),
                pred=pred,
                truth=truth,
                ctrl=ctrl,
                genes=genes,
                global_genes=global_genes_arr,
                feature_mode_used='deg',
                feature_dim=int(global_genes_arr.shape[0]),
                include_ctrl=True,
            )
            point_rows.extend(cur_points)
            metric_rows.append(cur_metric)

        if not point_rows or not metric_rows:
            continue
        points_df = pd.DataFrame(point_rows)
        metrics_df = pd.DataFrame(metric_rows).sort_values(['split_id', 'condition']).reset_index(drop=True)
        summary_df_local = condition_centroid_vis._summary_df(metrics_df)
        summary_df_local['model_name'] = 'systema_matching_mean'
        summary_df_local['dataset'] = dataset_key
        summary_df_local['dataset_label'] = next((spec['dataset_label'] for spec in DATASET_SPECS if spec['dataset_key'] == dataset_key), dataset_key.title())
        summary_df_local['split_id'] = int(split_id)
        summary_rows.append(summary_df_local)

        out_dir = target_root / f'systema_matching_mean_split{split_id}'
        out_dir.mkdir(parents=True, exist_ok=True)
        metrics_df.to_csv(out_dir / 'condition_centroid_metrics.csv', index=False)
        summary_df_local.to_csv(out_dir / 'condition_centroid_summary.csv', index=False)
        points_plot_df, meta = condition_centroid_vis._fit_umap(points_df, seed=24, umap_n_neighbors=None, umap_min_dist=0.15)
        points_plot_df.to_csv(out_dir / 'truth_pred_ctrl_centroid_umap.csv', index=False)
        delta_points = condition_centroid_vis._build_delta_points(metrics_df, points_df)
        delta_plot_df, delta_meta = condition_centroid_vis._fit_umap(delta_points, seed=24, umap_n_neighbors=None, umap_min_dist=0.15)
        delta_plot_df.to_csv(out_dir / 'condition_centroid_points.csv', index=False)
        condition_centroid_vis._plot_delta(
            delta_plot_df=delta_plot_df,
            out_path=out_dir / 'delta_centroid_umap.png',
            title=f'Matching mean:{dataset_key} split{split_id} | Delta centroid UMAP',
            save_dpi=420,
        )
        (out_dir / 'run_meta.json').write_text(
            _json.dumps({
                'model_name': 'systema_matching_mean',
                'dataset': dataset_key,
                'split_id': int(split_id),
                'embed_mode': delta_meta.get('embed_mode'),
                'umap_n_neighbors': delta_meta.get('n_neighbors'),
                'umap_min_dist': delta_meta.get('min_dist'),
            }, indent=2),
            encoding='utf-8',
        )

    if not summary_rows:
        return pd.DataFrame()
    return pd.concat(summary_rows, ignore_index=True)

systema_summary_df = _prepare_systema_assets('norman', SPLIT_IDS, OUT_ROOT)
summary_for_rep = summary_df.copy() if not summary_df.empty else pd.DataFrame()
if not systema_summary_df.empty:
    summary_for_rep = pd.concat([summary_for_rep, systema_summary_df], ignore_index=True)

metric_mean_df = pd.DataFrame()
if not summary_for_rep.empty:
    metric_mean_df = (
        summary_for_rep.groupby(['dataset', 'dataset_label', 'model_name'], as_index=False)[['centroid_dist_mean']]
        .mean()
    )
    metric_mean_df['display_name'] = metric_mean_df['model_name'].map(MODEL_DISPLAY).fillna(metric_mean_df['model_name'])
metric_mean_df.to_csv(OUT_ROOT / 'figs4_metric_means_5split.csv', index=False, encoding='utf-8-sig')

bar_df = metric_mean_df[metric_mean_df['dataset_label'].isin(DATASET_ORDER)].copy() if not metric_mean_df.empty else pd.DataFrame()
bar_df['dataset_label'] = pd.Categorical(bar_df['dataset_label'], categories=DATASET_ORDER, ordered=True) if not bar_df.empty else pd.Series(dtype=object)
bar_models = [m for m in MODEL_ORDER if m in set(bar_df['model_name'])] if not bar_df.empty else []
bar_labels = [MODEL_DISPLAY[m] for m in bar_models]

fig, ax = plt.subplots(1, 1, figsize=(7.6, 4.8), dpi=220)
if bar_df.empty or 'centroid_dist_mean' not in bar_df.columns:
    ax.text(0.5, 0.5, 'No rows for centroid_dist_mean', ha='center', va='center')
    ax.axis('off')
else:
    sns.barplot(
        data=bar_df,
        x='dataset_label',
        y='centroid_dist_mean',
        hue='display_name',
        order=DATASET_ORDER,
        hue_order=bar_labels,
        palette=MODEL_COLORS,
        ax=ax,
        saturation=0.95,
    )
    ax.set_title('Centroid distance mean')
    ax.set_xlabel('')
    ax.set_ylabel('5-split mean centroid distance')
    legend = ax.get_legend()
    if legend is not None:
        legend.remove()
    for patch in ax.patches:
        patch.set_edgecolor('white')
        patch.set_linewidth(0.7)
    apply_gears_paper_style(font_scale=1.0)
    ax.set_axisbelow(True)
    ax.grid(axis='y', alpha=0.25)
handles = [Patch(facecolor=MODEL_COLORS[label], edgecolor='white', label=label) for label in bar_labels]
if handles:
    fig.legend(handles=handles, loc='upper center', bbox_to_anchor=(0.5, 1.02), ncol=min(5, len(handles)), frameon=False, title='')
fig.suptitle('FigS4a: Five-split condition-centroid summary', y=1.06)
fig.tight_layout(rect=[0.0, 0.0, 1.0, 0.95])
fig.savefig(OUT_ROOT / 'figs4a_mean_metric_bars.png', bbox_inches='tight')
plt.close(fig)
display(metric_mean_df.head())

target_dataset = 'norman'
target_label = next((spec['dataset_label'] for spec in DATASET_SPECS if spec['dataset_key'] == target_dataset), target_dataset.title())
grid_models = [
    m for m in REPRESENTATIVE_MODEL_ORDER
    if (OUT_ROOT / target_dataset).exists() and any((OUT_ROOT / target_dataset / f'{m}_split{split_id}' / 'delta_centroid_umap.png').exists() for split_id in SPLIT_IDS)
]
grid_labels = [MODEL_DISPLAY[m] for m in grid_models]
representative_split = None
if not summary_for_rep.empty:
    rep_df = summary_for_rep[summary_for_rep['dataset'] == target_dataset].copy()
    rep_df = rep_df[rep_df['model_name'].isin(grid_models)].copy()
    if not rep_df.empty:
        split_means = rep_df.groupby('split_id', as_index=False)[['centroid_dist_mean']].mean()
        global_centroid_dist = split_means['centroid_dist_mean'].mean()
        split_means['rep_score'] = (split_means['centroid_dist_mean'] - global_centroid_dist).abs()
        representative_split = int(split_means.sort_values(['rep_score', 'split_id']).iloc[0]['split_id'])
if representative_split is None and SPLIT_IDS:
    representative_split = int(SPLIT_IDS[0])

pd.DataFrame([{'dataset': target_dataset, 'representative_split': representative_split}]).to_csv(OUT_ROOT / f'figs4b_{target_dataset}_representative_split.csv', index=False, encoding='utf-8-sig')

ncols = 2
nrows = int(np.ceil(max(1, len(grid_models)) / ncols))
fig, axes = plt.subplots(nrows, ncols, figsize=(8.8, 4.0 * nrows), dpi=220, squeeze=False)
flat_axes = axes.flatten()
for idx, model_name in enumerate(grid_models):
    ax = flat_axes[idx]
    img_path = OUT_ROOT / target_dataset / f'{model_name}_split{representative_split}' / 'delta_centroid_umap.png'
    if img_path.exists():
        img = plt.imread(img_path)
        if img.ndim >= 2:
            h, w = img.shape[:2]
            top = int(0.06 * h)
            bottom = int(0.98 * h)
            left = int(0.02 * w)
            right = int(0.99 * w)
            cropped = img[top:bottom, left:right]
            ax.imshow(cropped)
        else:
            ax.imshow(img)
    else:
        ax.text(0.5, 0.5, 'Missing', ha='center', va='center', fontsize=9)
    ax.set_xticks([])
    ax.set_yticks([])
    for spine in ax.spines.values():
        spine.set_visible(True)
        spine.set_linewidth(0.6)
        spine.set_edgecolor('#B5B5B5')
    ax.set_title(grid_labels[idx], fontsize=10, pad=6)
for idx in range(len(grid_models), len(flat_axes)):
    flat_axes[idx].axis('off')
fig.suptitle(f'FigS4b: {target_label} representative split (Split {representative_split})', y=0.995)
fig.tight_layout(rect=[0.01, 0.0, 1.0, 0.965])
fig.savefig(OUT_ROOT / f'figs4b_{target_dataset}_delta_centroid_grid.png', bbox_inches='tight')
plt.close(fig)

[embd] embedding index ready: key=embd_index
[degs] using precomputed degs: key=top20_degs_non_dropout

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
D:\conda_envs\biolord\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

   dataset dataset_label model_name  centroid_dist_mean display_name
0  adamson       Adamson    biolord            2.367398      biolord
1  adamson       Adamson      gears            1.300728        GEARS
2  adamson       Adamson   genepert            1.108634     GenePert
3  adamson       Adamson      scgpt            1.323989        scGPT
4  adamson       Adamson   trishift            0.969842     TriShift